name: drawings
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - decord
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pip
  - tensorboard
  - pillow
  - opencv
  - scikit-learn
  - pip:
     - oyaml
     - dominate
     - ninja
     - ftfy
     - tqdm
     - regex
